// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "SmartPeer | یادگیری هوشمند همتا‌محور",
//   description: "با SmartPeer، بهترین همتا و منتور آموزشی خود را پیدا کنید و مسیر یادگیری شخصی‌سازی‌شده خود را بسازید.",
//   keywords: "یادگیری همتا, منتورینگ, آموزش آنلاین, هوش مصنوعی آموزشی, peer learning",
// };

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="fa" dir="rtl">
//       <body className="min-h-screen bg-navy-950 text-white antialiased">
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "SmartPeer | یادگیری هوشمند همتا‌محور",
  description: "با SmartPeer، بهترین همتا و منتور آموزشی خود را پیدا کنید و مسیر یادگیری شخصی‌سازی‌شده خود را بسازید.",
  keywords: "یادگیری همتا, منتورینگ, آموزش آنلاین, هوش مصنوعی آموزشی, peer learning",
  openGraph: {
    title: "SmartPeer | یادگیری هوشمند همتا‌محور",
    description: "پلتفرم هوشمند یادگیری همتا‌محور با قدرت هوش مصنوعی",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" className="dark">
      <body className="min-h-screen bg-navy-950 text-white antialiased">
        {children}
      </body>
    </html>
  );
}
